server:
  address:
  port : 8080

app:
  pathToSaveWav : "/home/alan/Bureau"
  targetUrl: "http://127.0.0.1:5000/predict"

jdbc:
  driverclassname: "com.mysql.jdbc.Driver"
  Url: "jdbc:mysql://localhost:3306/parkinson?allowPublicKeyRetrieval=true&useSSL=false"
  Username: "admin"
  Password: "password"